# Documentation: https://github.com/compose-spec/compose-spec/blob/master/spec.md
# Purpose: Build local containers for the Mutillidae environment

version: '3.7'
services:

  database:
    container_name: database
    image: mysql:8.0.32
    environment:
      - MYSQL_ROOT_PASSWORD=mutillidae
      - MYSQL_DATABASE=mutillidae
    ports:
      - 3306:3306
    networks:
      - datanet

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - database
    image: phpmyadmin:latest
    environment:
      - MYSQL_ROOT_PASSWORD=mutillidae
      - PMA_HOST=database
      - PMA_USER=root
      - PMA_PASSWORD=mutillidae
    ports:
      - 127.0.0.1:81:80
    networks:
      - datanet

  apache:
    container_name: apache
    depends_on:
      - database
      - ldap
    image: mureevms/mutillidae:apache
    build:
        context: ./apache
        dockerfile: Dockerfile
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
    networks:
      - datanet
      - ldapnet

  ldap:
    container_name: ldap
    image: osixia/openldap:latest
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    environment:
      - LDAP_ORGANISATION=Mutillidae Inc
      - LDAP_DOMAIN=mutillidae.localhost
      - LDAP_BASE_DN=dc=mutillidae,dc=localhost
      - LDAP_ADMIN_PASSWORD=mutillidae
      - LDAP_CONFIG_PASSWORD=mutillidae
      - LDAP_TLS=false
    ports:
      - 127.0.0.1:389:389
    networks:
      - ldapnet

  ldap_admin:
    container_name: ldap_admin
    depends_on:
      - ldap
    image: osixia/phpldapadmin:latest
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=directory
      - PHPLDAPADMIN_HTTPS=false
    ports:
      - 127.0.0.1:82:80
    networks:
      - ldapnet

# Volumes to persist data used by the LDAP server
volumes:
  ldap_data:
  ldap_config:

# Create network segments for the containers to use
networks:
    datanet:
    ldapnet:
